### ISSUE TITLE
[SUGGESTION] Oredict seeds

### ISSUE THREAD

**Issue by Sunconure11** [luxtracon/floralis#74]
```
listAllseed
seed
listAllSeed
seeds
```

These are the oredict definitions for seeds. I'd advise putting these on the seeds for your plants in the next update.

**Comment by luxtracon** [comment]
Thanks for the advice. I already registered them with `seed` tho, but wasn't aware that there are more definitions than that.

**Comment by Sunconure11** [comment]
Don't add the unneeded suffix denoting the plant, just those definitions above will suffice.

So something like say, a purple cactus and a yellow flower would both have seeds under `seed`, not something like `seedYellowFlower`

**Comment by Sunconure11** [comment]
@luxtracon

**Comment by Sunconure11** [comment]
So uh, what became of my note?
