### ISSUE TITLE
Right click on seeded field does consume seed

### ISSUE THREAD

**Issue by zekroTJA** [luxtracon/floralis#79]
## Bug Description

When right-clicking on an already seeded field next to the crop hitbox, the seed is being consumed.

## Steps to reproduce

1. Create a field.
2. Plant any kind of floralis seed on the field.
3. Right-click with floralis seed in hand on the field next to the crop.

## Demonstration

https://user-images.githubusercontent.com/16734205/147388884-638b692a-d834-4fa7-96cc-02fce2de02f6.mp4

**Comment by luxtracon** [comment]
duplicate of #78
