### ISSUE TITLE
Floralis fails to load on server after 3.1.0

### ISSUE THREAD

**Issue by Raidobw2** [luxtracon/floralis#80]
Hi, I'm unable to run Floralis on a 1.18.2 Forge server after the 3.1.0 update. I'm using Forge 40.1.31. Attached is the server log which shows the error: https://paste.feed-the-beast.com/view/8ae4dd81. I believe that could be caused by mixins:
`[03:19:08] [main/FATAL] [mixin/]: Mixin apply failed floralis.mixins.json:FireBlockAccess -> net.minecraft.world.level.block.FireBlock: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching`.
The modlist is only composed of your mod:
![image](https://user-images.githubusercontent.com/17010632/172040311-40f0972d-9b96-437c-b01f-e83f482c877e.png)
Thanks in advance for checking it out and have a good day!

**Comment by luxtracon** [comment]
Thanks for the feedback! I tested both client and server as usual within my IDE before releasing the 3.1.0 and it both worked just fine there. Apparently Forge slightly altered the way mixins are read with the latest releases for 1.18.2. A simple addition should've fixed that now.

I also tested it out of my IDE this time and both client and server start and work just fine, still I'd like you to test it in your environment too and let me know if it works for you too, before I make a final public release on CurseForge. You can find the latest build with the fix [here](https://github.com/luxtracon/floralis/releases/tag/3.2.0).

**Comment by Raidobw2** [comment]
Hi, thanks for the reply! I've just tested this in a modpack amongst other mods, and it works great! No crash at all on 1.18.2, Forge 40.1.31. You can go ahead and release this to the public, this is fixed. Thanks a lot!
![image](https://user-images.githubusercontent.com/17010632/172264547-1d7fe4ca-a0ca-4188-9a9c-4bd74bd992fd.png)
