### ISSUE TITLE
[1.19.2] Jade Item Display

### ISSUE THREAD

**Issue by HalcyonSeas73** [luxtracon/floralis#81]
Floralis version: 6.2.0
Forge version: 43.1.1

Floralis' flower seeds show in Jade as being wheat seeds, even fully grown.
![image](https://user-images.githubusercontent.com/84727791/189510963-36970066-9e69-4ece-b951-8c06c7bf790e.png)

**Comment by luxtracon** [comment]
Thanks for reporting, I will take a look at it.

**Comment by luxtracon** [comment]
This will be fixed throughout the entire version range with the next update coming this week.
