### ISSUE TITLE
[1.19.2] Farmland Compatibility

### ISSUE THREAD

**Issue by HalcyonSeas73** [luxtracon/floralis#82]
Floralis version: 6.2.0
Forge version: 43.1.1

Floralis flower seeds seem to be incompatible with other mods' farmland (tested with Farmer's Delight's Rich Soil Farmland, and Mystical Agriculture's Essence Farmlands). Flower seeds cannot be planted on it.

**Comment by luxtracon** [comment]
Thanks for reporting, I will take a look at it.

**Comment by luxtracon** [comment]
This will be fixed throughout the entire version range with the next update coming this week.
